import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

try {
    if (prod) {
        // Production build - single build and exit
        await esbuild.build({
            banner: {
                js: banner,
            },
            entryPoints: ['main.ts'],
            bundle: true,
            external: [
                'obsidian',
                'electron',
                '@codemirror/autocomplete',
                '@codemirror/collab',
                '@codemirror/commands',
                '@codemirror/language',
                '@codemirror/lint',
                '@codemirror/search',
                '@codemirror/state',
                '@codemirror/view',
                '@lezer/common',
                '@lezer/highlight',
                '@lezer/lr',
                ...builtins
            ],
            format: 'cjs',
            target: 'es2018',
            logLevel: "info",
            sourcemap: false,
            treeShaking: true,
            outfile: 'main.js',
        });
        console.log('✅ Production build complete!');
    } else {
        // Development mode - watch for changes
        const context = await esbuild.context({
            banner: {
                js: banner,
            },
            entryPoints: ['main.ts'],
            bundle: true,
            external: [
                'obsidian',
                'electron',
                '@codemirror/autocomplete',
                '@codemirror/collab',
                '@codemirror/commands',
                '@codemirror/language',
                '@codemirror/lint',
                '@codemirror/search',
                '@codemirror/state',
                '@codemirror/view',
                '@lezer/common',
                '@lezer/highlight',
                '@lezer/lr',
                ...builtins
            ],
            format: 'cjs',
            target: 'es2018',
            logLevel: "info",
            sourcemap: 'inline',
            treeShaking: true,
            outfile: 'main.js',
        });
        
        await context.watch();
        console.log('👀 Watching for changes...');
    }
} catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
}